export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const ADD_USER = 'ADD_USER';
export const USER_REGISTRATION_FAILED = 'USER_REGISTRATION_FAILED';
export const USER_REGISTERING = 'USER_REGISTERING';